In [1]:
import pandas as pd
import numpy as np

In [2]:
english_data = pd.read_csv("data/lyrics_updated.csv")

In [3]:
english_data.head()

song  year           artist genre  \
0        ego-remix  2009  beyonce-knowles   Pop   
1     then-tell-me  2009  beyonce-knowles   Pop   
2          honesty  2009  beyonce-knowles   Pop   
3  you-are-my-rock  2009  beyonce-knowles   Pop   
4    black-culture  2009  beyonce-knowles   Pop   

                                              lyrics  \
0  Oh baby, how you doing?\nYou know I'm gonna cu...   
1  playin' everything so easy,\nit's like you see...   
2  If you search\nFor tenderness\nIt isn't hard t...   
3  Oh oh oh I, oh oh oh I\n[Verse 1:]\nIf I wrote...   
4  Party the people, the people the party it's po...   

                                      cleaned_lyrics  length lang  
0  oh baby how you doing you know i m gonna cut r...    1913   en  
1  playin everything so easy it s like you seem s...    1234   en  
2  if you search for tenderness it isn t hard to ...     820   en  
3  oh oh oh i oh oh oh i verse if i wrote a book ...    2293   en  
4  party the people the people the party it s pop...    1484   en

In [4]:
english_data = english_data[english_data['lang'] == 'en']

In [8]:
with open('data/english_lyrics.txt', 'a') as f:
    f.write(english_data['lyrics'].to_string(header=False,index=False))

In [27]:
pratik_hindi_lyrics = pd.read_csv("data/hindilyrics_pratik.csv")
pratik_hindi_lyrics.head()

Song  \
0  इट्स मैजिक, इट्स मैजिक\nकच्चा नहीं कुछ भी, पक्...   
1  जादू, जादू, जादू\n\nआज धरती से गगन का\nफूलों स...   
2  ख्वाबों, ख्यालों, ख्वाहिशों को चेहरा मिला\nमेर...   
3  इन पंछियों को देख कर\nजागे हैं ये अरमाँधरती पे...   
4  आँख मिला के पूछे\nहाई हाऊ आर यू\n(हाई हाऊ आर य...   

           SongTitleEnglish       SongTitleHindi  Year           MovieEnglish  \
0                It's Magic           इट्स मैजिक  2003           Koi Mil Gaya   
1                    Jaadoo                 जादू  2003           Koi Mil Gaya   
2              Koi Mil Gaya          कोई मिल गया  2003                  Title   
3  In Panchhiyon Ko Dekhkar  इन पंछियों को देखकर  2003           Koi Mil Gaya   
4           Shehar Ki Ladki          शहर की लड़की  2019   Khandaani Shafakhana   

        MovieHindi Music Director                  Lyricist  \
0      कोई मिल गया     राजेश रोशन             इब्राहिम अश्क़   
1      कोई मिल गया     राजेश रोशन             इब्राहिम अश्क़   
2      कोई मिल गया     राजेश रोशन             इब्राहिम अश्क़   
3      कोई मिल गया     राजेश रोशन             इब्राहिम अश्क़   
4  खानदानी शफाखाना   तनिष्क बागची  तनिष्क बागची, दीपक चौधरी   

                                      SingersEnglish  \
0                                       T.S. Jarnail   
1                         Alka Yagnik,  Udit Narayan   
2                         Chitra K.S.,  Udit Narayan   
3          Shaan,  Baby Sneha,  Kavita Krishnamurthy   
4  Badshah,  Anand-Milind,  Tulsi,  Abhijeet,  Ch...   

                                        SingersHindi  
0                                       टी.एस. जरनैल  
1                         अल्का याग्निक, उदित नारायण  
2                         चित्रा के.एस., उदित नारायण  
3                शान, बेबी स्नेहा, कविता कृष्णमूर्ति  
4  बादशाह, आनंद-मिलिंद, तुलसी कुमार, अभिजीत, चंद्...

In [29]:
with open('data/pratik_hindi_lyrics.txt', 'a') as f:
    f.write(pratik_hindi_lyrics['Song'].to_string(header=False,index=False))

In [32]:
import numpy as np
dim = 1024

In [ ]:
hindi = np.fromfile("data/embeddings/pratik_hindi_embeddings.raw", dtype=np.float32, count=-1)                                                                          
hindi.resize(hindi.shape[0] // dim, dim)

In [33]:
english = np.fromfile("data/embeddings/english_embeddings.raw", dtype=np.float32, count=-1)                                                                          
english.resize(english.shape[0] // dim, dim)

In [34]:
d=1024
import faiss                   # make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(hindi)                  # add vectors to the index
print(index.ntotal)

True
3859


In [51]:
k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(english[5:7], k) 
print(I)
print(D)

[[1903 1789 1170 2255]
 [1795 1889  990 1655]]
[[0.17250746 0.17963707 0.18236226 0.18632814]
 [0.18957865 0.19034299 0.19462848 0.19498357]]


In [46]:
for song in pratik_hindi_lyrics.iloc[[407, 3638, 1621, 2567]]['Song']:
    print(song)
    print("--------------------------------------")

उह, आह
बेबी लेट मी लव यू
उह, आह
बेबी लेट मी किस यू
उह, आह
बेबी लेट मी हग यू
उह, आह
बेबी लेट मी लव यू

इन बाज़ुओं में जो ले लो मुझे
तो चैन शायद मिले
आओ मिटा भी दो अब तो मेरे
तन मन के सारे गिले
मैं हूँ तरसी तरसी
तरसा तरसा है ये मन
क्या कहूँ जानेमन
जलता है क्यूँ ये बदन
उह, आह
बेबी लेट मी लव यू...

देखो धीमे धीमे
हाँ कैसे होश खो गए
हो, तुम तो धीरे धीरे
हाँ बस मेरे हो गए
बेचैनियाँ और मैं हूँ
बेताबियाँ और मैं हूँ
मीठी सी, हर अंग में है थकन
क्या कहूँ जानेमन...

मैं हूँ बावली सी
हाँ तुम भी हो मनचले
हम्म, देखो मिटने ही थे
हाँ जो भी थे फासले
अब ना कोई मैं और ना तुम
इक दूसरे में दोनों गुम
कैसी है, दीवाने दिल की लगन
क्या कहूँ जानेमन...
--------------------------------------
मैं तन हारा, मैं मन हारा, मैं जां हारा, मैं जग हारा
होश भी हारा, जोश भी हारा
मैं सब हारा...
बावरे...
बाजे ढोल अर तासा रे, खा के दूध बतासा रे
आयो मु की बासा रे, देखो देखो तमासा रे
हो रंगीले रंगीले पल है, चमकीले चमकीले पल है
बरसे झिलमिल करते लाखों तारे
अलबेले अलबेले तन है, लचकीले लचकीले तन है
कोई अपना दिल कैसे ना हारे
हो मैं तन ह

In [49]:
english_data.iloc[3]['lyrics'].split('\n')

['Oh oh oh I, oh oh oh I',
 '[Verse 1:]',
 'If I wrote a book about where we stand',
 'Then the title of my book would be "Life with Superman"',
 "That's how you make me feel I count you as a privilege",
 'This love is so ideal',
 "I'm honored to be in it",
 'I know you feel the same I see it everyday',
 'In all the things you do',
 'In all the things you say',
 '[Chorus:]',
 'You are my rock',
 "Baby you're the truth",
 'You are my rock',
 'I love to rock with you',
 'You are my rock',
 "You're everything I need",
 'You are my rock',
 'So baby rock with me',
 'I wanna kiss ya, feel ya, please ya just right',
 'I wanna touch ya, love ya, baby all night',
 'Reward ya, for all the things you do',
 'You are my rock',
 'I love to rock with you',
 'I love to rock with you',
 'Oh oh oh I',
 '[Verse 2:]',
 'If I were to try to count the ways',
 'You make me smile',
 "I'd run out of fingers",
 'Before I run out of timeless things to talk about',
 'Sugar you keeps it going on',
 'Make me wanna 

In [55]:
for song in pratik_hindi_lyrics.iloc[[1795, 1889,  990, 1655]]['Song']:
    print(song)
    print("--------------------------------------")

तू नज़्म-नज़्म सा मेरे
होंठो पे ठहर जा
मैं ख्वाब ख्वाब सा तेरी
आँखों में जागूँ रे
तू इश्क-इश्क सा मेरे
रूह में आ के बस जा
जिस ओर तेरी शहनाई
उस ओर मैं भागूँ रे

हाथ थाम ले पिया, करते हैं वादा
अब से तू आरज़ू, तू ही है इरादा
मेरा नाम ले पिया, मैं तेरी रुबाई
तेरे ही तो पीछे-पीछे बरसात आई
तू इत्र-इत्र सा मेरे
साँसों में बिखर जा
मैं फ़कीर तेरे कुर्बत का
तुझसे तू मांगू रे
तू इश्क-इश्क सा...

मेरे दिल के लिफाफे में
तेरा ख़त है जाणिया, तेरा ख़त है जाणिया
नाचीज़ ने कैसे पा ली, क़िस्मत ये जाणिया वे
तू नज़्म-नज़्म सा...

हीर नी मेरिये, हीर नी मेरिये
तुझको ही मैं चाहूँ
कोशिशाँ मैं करिए
तुझको भूल ना पाऊँ
--------------------------------------
सजना जी वारी-वारी जाऊँ जी मैं
तू ही तो मेरा संसार है, ऐसा मेरा प्यार है
चरणों में जो ना जगह पाऊँ जी मैं
तो मेरा जीना ही बेकार है
ऐसा मेरा प्यार है...

मेरा मान है तू, अभिमान है तू
मेरी पूजा है तू, मेरा ध्यान है तू
तू देवता मैं पुजारन, सजना तुझपे मैं अर्पण
तेरे गुणगान ही तो गाऊँ जी मैं
तू ही तो मेरा संसार...

ओ मेरी धड़कन में तू, मेरे तण-मण में तू
मेरी साँसों में तू, मेरे 

In [54]:
english_data.iloc[6]['lyrics'].split('\n')

['This is just another day that I would spend',
 "Waitin' for the right one.",
 "Staring at the night and wishin' I could be the one",
 'To feel the warm sun.',
 "You're a dream, but I'm wide awake",
 "I'm in Heaven, for heaven sakes",
 "So get ready, (get ready) I'm ready now (get ready)",
 'I could never need you more than now',
 'You were worth waiting for',
 'You the one that I adore',
 'Hold on to me tight',
 'For once in my life',
 'You were worth waiting for',
 'You the one that I adore',
 "This kind of love you'll only find",
 'Once in a lifetime, once in a lifetime',
 'Tell me that your living in a place',
 'Where no one else can find you.',
 'Tell me that your sanging out my name,',
 "Hoping that I'll hear you.",
 'Tell me "No" and I\'ll fade away,',
 "But this is lovin that I won't waste",
 "So get ready, (get ready) I'm ready now (get ready)",
 'I could never need you more than now',
 'You were worth waiting for',
 'You the one that I adore',
 'hold on to me tight',
 'For o